Выполнены все задания, но не получилось добавить в изображения источн…
Husky022/geekshop pull request #2
Opened 2021-01-27 21:54 UTC by Husky022

…ик картинки с динамической папкой static:

"img": "{% static 'vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png'%}" (специально для наглядности оставил в одном товаре запись такого вида. Там не прогрузилась картинка) Прошу подсказать, в чем может быть косяк)

2021-01-28 11:11 UTC, Vokler requested changes

2021-01-28 11:11 UTC, Vokler commented on mainapp/fixtures/products.json
> +    "img": "{% static 'vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png'%}"
Здесь проблема в том, что вы пытаетесь передать в img placeholder в виде шаблонного тега. Предыдущие примеры верные.
Либо в шаблоне нужно было сделать `img="{% static product.img %}"`, где product.img - это `vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png`

2021-01-29 06:40 UTC, Husky022 commented on mainapp/fixtures/products.json
> +    "img": "{% static 'vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png'%}"
Подправил файл products.json и products.html

2021-01-29 09:15 UTC, Vokler commented
У вас конфликты с master веткой. Чтобы решить проблему и мы могли смержить, откройте ветку Lesson2 в PyCharm и сделайте в нее git pull master
![image](https://user-images.githubusercontent.com/21297042/106255926-b1bcfa80-622b-11eb-8513-cb6cb62caa9c.png)

2021-02-01 13:12 UTC, Husky022 commented
в Pycharm в ветку Lesson2 выполнил Pull из master. Конфликта не возникло

2021-02-03 10:18 UTC, Husky022 commented
Подправил

2021-02-03 18:05 UTC, merged